### ISSUE TITLE
cannot render layouts

### ISSUE THREAD

**Issue by flippyhead** [mauricemach/coffeekup#6]
I cannot get layouts to render. It finds the views/layout.coffee file, but errors with:

TypeError: string is not a function
    at String.CALL_NON_FUNCTION (native)
    at Object.anonymous (eval at <anonymous> (/usr/local/lib/node/.npm/coffeekup/0.1.7/package/lib/coffeekup.js:139:25))
    at Object.render (/usr/local/lib/node/.npm/coffeekup/0.1.7/package/lib/coffeekup.js:144:21)
    at ServerResponse.render (/usr/local/lib/node/.npm/express/1.0.0rc4/package/lib/express/view.js:293:26)
    at ServerResponse.render (/usr/local/lib/node/.npm/express/1.0.0rc4/package/lib/express/view.js:303:14)
    at Object.<anonymous> (server.coffee (compiled):33:16)
    at pass (/usr/local/lib/node/.npm/connect/0.2.7/package/lib/connect/middleware/router.js:72:27)
    at Object.router [as handle](/usr/local/lib/node/.npm/connect/0.2.7/package/lib/connect/middleware/router.js:87:10)
    at next (/usr/local/lib/node/.npm/connect/0.2.7/package/lib/connect/index.js:264:23)
    at /usr/local/lib/node/.npm/connect/0.2.7/package/lib/connect/middleware/session.js:140:15

**Comment by mauricemach** [comment]
Does the example at /examples/express work for you?

**Comment by flippyhead** [comment]
No, that's what I'm using. If I remove everything but something like:

h1 @body

It works..

**Comment by mauricemach** [comment]
I see you're on 0.1.7. Can you give 0.2.0 a try?

What version is your CoffeeScript?

**Comment by flippyhead** [comment]
Don't know why, but that did it! Thank you

**Comment by mauricemach** [comment]
No problem. If you stumble upon further issues, let me know!
