### ISSUE TITLE
Can't install via npm

### ISSUE THREAD

**Issue by benekastah** [mauricemach/coffeekup#73]
Apparently it is having trouble decompressing package.tgz. I am running Mac OS X 10.7.

Here is the full contents of my `npm-debug.log` file.

```
info it worked if it ends with ok
verbose cli [ 'node',
verbose cli   '/usr/local/bin/npm',
verbose cli   'install',
verbose cli   '-g',
verbose cli   'coffeekup' ]
info using npm@1.0.9-1
info using node@v0.4.11
verbose /usr/local/bin/node node symlink
verbose config file /Users/Paul/.npmrc
verbose config file /usr/local/etc/npmrc
verbose into /usr/local/lib [ 'coffeekup' ]
verbose cache add [ 'coffeekup', null ]
info addNamed [ 'coffeekup', '' ]
verbose addNamed [ null, '' ]
verbose GET coffeekup
verbose raw, before any munging coffeekup
verbose url resolving [ 'http://registry.npmjs.org/', './coffeekup' ]
verbose url resolved http://registry.npmjs.org/coffeekup
verbose url parsed { protocol: 'http:',
verbose url parsed   slashes: true,
verbose url parsed   host: 'registry.npmjs.org',
verbose url parsed   hostname: 'registry.npmjs.org',
verbose url parsed   href: 'http://registry.npmjs.org/coffeekup',
verbose url parsed   pathname: '/coffeekup' }
verbose etag "B6M1DVI7J0LZ2FRYEJBMIZMM"
verbose response http://registry.npmjs.org/coffeekup
silly get cb [ 304,
silly get cb   { server: 'CouchDB/1.1.0 (Erlang OTP/R14B03)',
silly get cb     etag: '"B6M1DVI7J0LZ2FRYEJBMIZMM"',
silly get cb     date: 'Fri, 09 Sep 2011 02:52:57 GMT',
silly get cb     'content-length': '0' } ]
verbose etag coffeekup from cache
verbose GET coffeekup/0.3.0
verbose raw, before any munging coffeekup/0.3.0
verbose url resolving [ 'http://registry.npmjs.org/', './coffeekup/0.3.0' ]
verbose url resolved http://registry.npmjs.org/coffeekup/0.3.0
verbose url parsed { protocol: 'http:',
verbose url parsed   slashes: true,
verbose url parsed   host: 'registry.npmjs.org',
verbose url parsed   hostname: 'registry.npmjs.org',
verbose url parsed   href: 'http://registry.npmjs.org/coffeekup/0.3.0',
verbose url parsed   pathname: '/coffeekup/0.3.0' }
verbose etag "B6M1DVI7J0LZ2FRYEJBMIZMM"
verbose response http://registry.npmjs.org/coffeekup/0.3.0
silly get cb [ 304,
silly get cb   { server: 'CouchDB/1.1.0 (Erlang OTP/R14B03)',
silly get cb     etag: '"B6M1DVI7J0LZ2FRYEJBMIZMM"',
silly get cb     date: 'Fri, 09 Sep 2011 02:53:17 GMT',
silly get cb     'content-length': '0' } ]
verbose etag coffeekup/0.3.0 from cache
verbose bin dist [ '0.4-ares1.7.4-ev4.4-openssl0.9.8r-v83.1.8.26-darwin-11.1.0',
verbose bin dist   { shasum: 'eee40a3b3402b49327f9895731c20b94c092aff4',
verbose bin dist     tarball: 'http://registry.npmjs.org/coffeekup/-/coffeekup-0.3.0.tgz' } ]
silly resolved [ { name: 'coffeekup',
silly resolved     description: 'Markup as CoffeeScript.',
silly resolved     version: '0.3.0',
silly resolved     author: 
silly resolved      { name: 'Maurice Machado',
silly resolved        email: 'maurice@bitbending.com' },
silly resolved     homepage: 'http://coffeekup.org',
silly resolved     repository: 
silly resolved      { type: 'git',
silly resolved        url: 'git://github.com/mauricemach/coffeekup.git' },
silly resolved     dependencies: { 'coffee-script': '>= 1.1.2' },
silly resolved     devDependencies: 
silly resolved      { jade: '0.13.0',
silly resolved        eco: '1.1.0-rc-1',
silly resolved        ejs: '0.4.3',
silly resolved        haml: '0.4.2' },
silly resolved     keywords: [ 'template', 'view', 'coffeescript' ],
silly resolved     bin: { coffeekup: './bin/coffeekup' },
silly resolved     main: './lib/coffeekup',
silly resolved     engines: { node: '>= 0.4.7' },
silly resolved     contributors: 
silly resolved      [ { name: 'Luis Pedro Coelho', email: 'lpc@cmu.edu' },
silly resolved        { name: 'Rachel Carvalho',
silly resolved          email: 'rachel.carvalho@gmail.com' },
silly resolved        { name: 'Vladimir Dronnikov',
silly resolved          email: 'dronnikov@gmail.com' },
silly resolved        { name: 'James Campos',
silly resolved          email: 'james.r.campos@gmail.com' },
silly resolved        { name: 'Martin Westergaard Lassen',
silly resolved          email: 'martin@mwl.dk' },
silly resolved        { name: 'Esa-Matti Suuronen',
silly resolved          email: 'esa-matti@suuronen.org' },
silly resolved        { name: 'Jason King', email: 'jasonk@amcoonline.net' },
silly resolved        { name: 'Brandon Bloom',
silly resolved          email: 'brandon@brandonbloom.name' },
silly resolved        { name: 'Nicholas Kinsey',
silly resolved          email: 'nicholas.kinsey@feistystudios.com' } ],
silly resolved     _npmJsonOpts: 
silly resolved      { file: '/Users/mauricemach/.npm/coffeekup/0.3.0/package/package.json',
silly resolved        wscript: false,
silly resolved        contributors: false,
silly resolved        serverjs: false },
silly resolved     _id: 'coffeekup@0.3.0',
silly resolved     _engineSupported: true,
silly resolved     _npmVersion: '1.0.23',
silly resolved     _nodeVersion: 'v0.4.11',
silly resolved     _defaultsLoaded: true,
silly resolved     dist: 
silly resolved      { shasum: 'eee40a3b3402b49327f9895731c20b94c092aff4',
silly resolved        tarball: 'http://registry.npmjs.org/coffeekup/-/coffeekup-0.3.0.tgz' },
silly resolved     scripts: {},
silly resolved     maintainers: 
silly resolved      [ { name: 'mauricemach',
silly resolved          email: 'maurice@bitbending.com' } ],
silly resolved     directories: {} } ]
info into /usr/local/lib coffeekup@0.3.0
info installOne coffeekup@0.3.0
info unbuild /usr/local/lib/node_modules/coffeekup
info addNamed [ 'coffeekup', '0.3.0' ]
verbose addNamed [ '0.3.0', '0.3.0' ]
verbose GET coffeekup/0.3.0
verbose raw, before any munging coffeekup/0.3.0
verbose url resolving [ 'http://registry.npmjs.org/', './coffeekup/0.3.0' ]
verbose url resolved http://registry.npmjs.org/coffeekup/0.3.0
verbose url parsed { protocol: 'http:',
verbose url parsed   slashes: true,
verbose url parsed   host: 'registry.npmjs.org',
verbose url parsed   hostname: 'registry.npmjs.org',
verbose url parsed   href: 'http://registry.npmjs.org/coffeekup/0.3.0',
verbose url parsed   pathname: '/coffeekup/0.3.0' }
verbose etag "B6M1DVI7J0LZ2FRYEJBMIZMM"
verbose response http://registry.npmjs.org/coffeekup/0.3.0
silly get cb [ 304,
silly get cb   { server: 'CouchDB/1.1.0 (Erlang OTP/R14B03)',
silly get cb     etag: '"B6M1DVI7J0LZ2FRYEJBMIZMM"',
silly get cb     date: 'Fri, 09 Sep 2011 02:53:37 GMT',
silly get cb     'content-length': '0' } ]
verbose etag coffeekup/0.3.0 from cache
verbose bin dist [ '0.4-ares1.7.4-ev4.4-openssl0.9.8r-v83.1.8.26-darwin-11.1.0',
verbose bin dist   { shasum: 'eee40a3b3402b49327f9895731c20b94c092aff4',
verbose bin dist     tarball: 'http://registry.npmjs.org/coffeekup/-/coffeekup-0.3.0.tgz' } ]
verbose mkdir done: /usr/local/lib/node_modules/___coffeekup.npm 755
verbose unpack_ uid, gid [ undefined, undefined ]
verbose unpackTarget /usr/local/lib/node_modules/coffeekup
silly gunzTarPerm modes [ '755', '644' ]
ERR! gzip "--decompress" "--stdout" "/Users/Paul/.npm/coffeekup/0.3.0/package.tgz" 
ERR! gzip "--decompress" "--stdout" "/Users/Paul/.npm/coffeekup/0.3.0/package.tgz" gzip: /Users/Paul/.npm/coffeekup/0.3.0/package.tgz: decompression OK, trailing garbage ignored
ERR! gzip "--decompress" "--stdout" "/Users/Paul/.npm/coffeekup/0.3.0/package.tgz" 
ERR! Failed unpacking /Users/Paul/.npm/coffeekup/0.3.0/package.tgz
ERR! error installing coffeekup@0.3.0 Error: Failed gzip "--decompress" "--stdout" "/Users/Paul/.npm/coffeekup/0.3.0/package.tgz"
ERR! error installing coffeekup@0.3.0 exited with 2
ERR! error installing coffeekup@0.3.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:77:19)
ERR! error installing coffeekup@0.3.0     at ChildProcess.emit (events.js:67:17)
ERR! error installing coffeekup@0.3.0     at ChildProcess.onexit (child_process.js:192:12)
info unbuild /usr/local/lib/node_modules/coffeekup
verbose installOne cb coffeekup@0.3.0
ERR! Error: Failed gzip "--decompress" "--stdout" "/Users/Paul/.npm/coffeekup/0.3.0/package.tgz"
ERR! exited with 2
ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:77:19)
ERR!     at ChildProcess.emit (events.js:67:17)
ERR!     at ChildProcess.onexit (child_process.js:192:12)
ERR! Report this *entire* log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR! 
ERR! System Darwin 11.1.0
ERR! command "node" "/usr/local/bin/npm" "install" "-g" "coffeekup"
verbose exit [ 1, true ]

```

**Comment by mauricemach** [comment]
I guess this an npm bug, I'm on OS X 10.7.1 and node 0.4.11, and I can install coffeekup fine. First thing I'd try is to update npm (mine is 1.0.27). Also, can you install other packages?

**Comment by benekastah** [comment]
Yeah, other packages seem to work fine (for the most part). I'm on version 1.0.9-1, so I'll try updating, and see if that helps.

---

**Edit:** updated to 1.0.27 and it's working now.
