### ISSUE TITLE
Problems with basic layout Unexpected 'CALL_START'

### ISSUE THREAD

**Issue by flexd** [mauricemach/coffeekup#93]
Hi there!

``` coffeescript

doctype 5
html ->
  head ->
    meta charset: 'utf-8'
    title "#{@title or 'Untitled'} | cognitive.io"
    meta(name: 'description', content: @desc) if @desc?
    link rel: 'stylesheet', href: '/stylesheets/app.css'
    script src: '/socket.io/socket.io.js'
    script src: '/zappa/jquery.js'
  body ->
    header ->
      h1 @title or 'Untitled'
    @body
```

That simple little layout (basically taken directly from the crashcourse) is giving me the error 

``` error

TemplateError: Error compiling /home/kristoffer/apps/cognitive.io/views/29d92364-74aa-4846-80fe-15c7061e939f/layout.coffee: Parse error on line 5: Unexpected 'CALL_START'
    at Object.compile (/home/kristoffer/apps/cognitive.io/node_modules/zappa/node_modules/coffeekup/lib/coffeekup.js:398:19)
    at Object.compile (/home/kristoffer/apps/cognitive.io/node_modules/zappa/lib/zappa.js:691:27)
    at Function.compile (/home/kristoffer/apps/cognitive.io/node_modules/zappa/node_modules/express/lib/view.js:65:33)
    at ServerResponse._render (/home/kristoffer/apps/cognitive.io/node_modules/zappa/node_modules/express/lib/view.js:414:18)
    at ServerResponse.render (/home/kristoffer/apps/cognitive.io/node_modules/zappa/node_modules/express/lib/view.js:315:17)
    at ServerResponse._render (/home/kristoffer/apps/cognitive.io/node_modules/zappa/node_modules/express/lib/view.js:429:10)
    at ServerResponse.render (/home/kristoffer/apps/cognitive.io/node_modules/zappa/node_modules/express/lib/view.js:315:17)
    at Object.<anonymous> (/home/kristoffer/apps/cognitive.io/node_modules/zappa/lib/zappa.js:445:33)
    at Object.render (/home/kristoffer/apps/cognitive.io/node_modules/zappa/lib/zappa.js:405:31)
    at Object.<anonymous> (/home/kristoffer/apps/cognitive.io/app.coffee:6:21)
```

And I have really no idea WHY it is doing this, what am I doing wrong?

The only thing the app.coffee does is serve '/ :-/

**Comment by flexd** [comment]
I must be doing something very wrong, this happens if I have more than one line/item inside head.

I can get other things to work that look pretty much identical but that exact layout does not work for some reason. I must have some sort of odd character or something in there?

**Comment by flexd** [comment]
Apparently this is a issue with Coffeescript and tabs/spaces/outtabbing. 

Editor is to blame I guess!
